package szu.csbd.dto;

import java.util.Date;

public class CommentsLiked {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments_like.comment_like_id
     *
     * @mbggenerated
     */
    private Integer commentLikeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments_like.offer_comment_id
     *
     * @mbggenerated
     */
    private Integer offerCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments_like.comment_liked
     *
     * @mbggenerated
     */
    private Boolean commentLiked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments_like.comment_liked_time
     *
     * @mbggenerated
     */
    private Date commentLikedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments_like.imei
     *
     * @mbggenerated
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments_like.ip_address
     *
     * @mbggenerated
     */
    private String ipAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments_like.comment_like_id
     *
     * @return the value of t_comments_like.comment_like_id
     *
     * @mbggenerated
     */
    public Integer getCommentLikeId() {
        return commentLikeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments_like.comment_like_id
     *
     * @param commentLikeId the value for t_comments_like.comment_like_id
     *
     * @mbggenerated
     */
    public void setCommentLikeId(Integer commentLikeId) {
        this.commentLikeId = commentLikeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments_like.offer_comment_id
     *
     * @return the value of t_comments_like.offer_comment_id
     *
     * @mbggenerated
     */
    public Integer getOfferCommentId() {
        return offerCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments_like.offer_comment_id
     *
     * @param offerCommentId the value for t_comments_like.offer_comment_id
     *
     * @mbggenerated
     */
    public void setOfferCommentId(Integer offerCommentId) {
        this.offerCommentId = offerCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments_like.comment_liked
     *
     * @return the value of t_comments_like.comment_liked
     *
     * @mbggenerated
     */
    public Boolean getCommentLiked() {
        return commentLiked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments_like.comment_liked
     *
     * @param commentLiked the value for t_comments_like.comment_liked
     *
     * @mbggenerated
     */
    public void setCommentLiked(Boolean commentLiked) {
        this.commentLiked = commentLiked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments_like.comment_liked_time
     *
     * @return the value of t_comments_like.comment_liked_time
     *
     * @mbggenerated
     */
    public Date getCommentLikedTime() {
        return commentLikedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments_like.comment_liked_time
     *
     * @param commentLikedTime the value for t_comments_like.comment_liked_time
     *
     * @mbggenerated
     */
    public void setCommentLikedTime(Date commentLikedTime) {
        this.commentLikedTime = commentLikedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments_like.imei
     *
     * @return the value of t_comments_like.imei
     *
     * @mbggenerated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments_like.imei
     *
     * @param imei the value for t_comments_like.imei
     *
     * @mbggenerated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments_like.ip_address
     *
     * @return the value of t_comments_like.ip_address
     *
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments_like.ip_address
     *
     * @param ipAddress the value for t_comments_like.ip_address
     *
     * @mbggenerated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }
}