package szu.csbd.dto;

import java.util.Date;

public class OfferCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_company.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_company.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_company.company_domain
     *
     * @mbggenerated
     */
    private Integer companyDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_company.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_company.imei
     *
     * @mbggenerated
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_company.ip_address
     *
     * @mbggenerated
     */
    private String ipAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_company.company_id
     *
     * @return the value of t_offer_company.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_company.company_id
     *
     * @param companyId the value for t_offer_company.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_company.company_name
     *
     * @return the value of t_offer_company.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_company.company_name
     *
     * @param companyName the value for t_offer_company.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_company.company_domain
     *
     * @return the value of t_offer_company.company_domain
     *
     * @mbggenerated
     */
    public Integer getCompanyDomain() {
        return companyDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_company.company_domain
     *
     * @param companyDomain the value for t_offer_company.company_domain
     *
     * @mbggenerated
     */
    public void setCompanyDomain(Integer companyDomain) {
        this.companyDomain = companyDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_company.add_time
     *
     * @return the value of t_offer_company.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_company.add_time
     *
     * @param addTime the value for t_offer_company.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_company.imei
     *
     * @return the value of t_offer_company.imei
     *
     * @mbggenerated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_company.imei
     *
     * @param imei the value for t_offer_company.imei
     *
     * @mbggenerated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_company.ip_address
     *
     * @return the value of t_offer_company.ip_address
     *
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_company.ip_address
     *
     * @param ipAddress the value for t_offer_company.ip_address
     *
     * @mbggenerated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }
}