package szu.csbd.dto;

import java.util.Date;

public class OfferDelay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_delay.offer_id
     *
     * @mbggenerated
     */
    private Integer offerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_delay.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_delay.salary
     *
     * @mbggenerated
     */
    private String salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_delay.work_position
     *
     * @mbggenerated
     */
    private String workPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_delay.work_address
     *
     * @mbggenerated
     */
    private String workAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_delay.sex
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_delay.school_name
     *
     * @mbggenerated
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_delay.education
     *
     * @mbggenerated
     */
    private Byte education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_delay.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_delay.delay_time
     *
     * @mbggenerated
     */
    private Date delayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_delay.imei
     *
     * @mbggenerated
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_delay.ip_address
     *
     * @mbggenerated
     */
    private String ipAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_delay.offer_id
     *
     * @return the value of t_offer_delay.offer_id
     *
     * @mbggenerated
     */
    public Integer getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_delay.offer_id
     *
     * @param offerId the value for t_offer_delay.offer_id
     *
     * @mbggenerated
     */
    public void setOfferId(Integer offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_delay.company_id
     *
     * @return the value of t_offer_delay.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_delay.company_id
     *
     * @param companyId the value for t_offer_delay.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_delay.salary
     *
     * @return the value of t_offer_delay.salary
     *
     * @mbggenerated
     */
    public String getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_delay.salary
     *
     * @param salary the value for t_offer_delay.salary
     *
     * @mbggenerated
     */
    public void setSalary(String salary) {
        this.salary = salary == null ? null : salary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_delay.work_position
     *
     * @return the value of t_offer_delay.work_position
     *
     * @mbggenerated
     */
    public String getWorkPosition() {
        return workPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_delay.work_position
     *
     * @param workPosition the value for t_offer_delay.work_position
     *
     * @mbggenerated
     */
    public void setWorkPosition(String workPosition) {
        this.workPosition = workPosition == null ? null : workPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_delay.work_address
     *
     * @return the value of t_offer_delay.work_address
     *
     * @mbggenerated
     */
    public String getWorkAddress() {
        return workAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_delay.work_address
     *
     * @param workAddress the value for t_offer_delay.work_address
     *
     * @mbggenerated
     */
    public void setWorkAddress(String workAddress) {
        this.workAddress = workAddress == null ? null : workAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_delay.sex
     *
     * @return the value of t_offer_delay.sex
     *
     * @mbggenerated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_delay.sex
     *
     * @param sex the value for t_offer_delay.sex
     *
     * @mbggenerated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_delay.school_name
     *
     * @return the value of t_offer_delay.school_name
     *
     * @mbggenerated
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_delay.school_name
     *
     * @param schoolName the value for t_offer_delay.school_name
     *
     * @mbggenerated
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_delay.education
     *
     * @return the value of t_offer_delay.education
     *
     * @mbggenerated
     */
    public Byte getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_delay.education
     *
     * @param education the value for t_offer_delay.education
     *
     * @mbggenerated
     */
    public void setEducation(Byte education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_delay.remark
     *
     * @return the value of t_offer_delay.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_delay.remark
     *
     * @param remark the value for t_offer_delay.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_delay.delay_time
     *
     * @return the value of t_offer_delay.delay_time
     *
     * @mbggenerated
     */
    public Date getDelayTime() {
        return delayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_delay.delay_time
     *
     * @param delayTime the value for t_offer_delay.delay_time
     *
     * @mbggenerated
     */
    public void setDelayTime(Date delayTime) {
        this.delayTime = delayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_delay.imei
     *
     * @return the value of t_offer_delay.imei
     *
     * @mbggenerated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_delay.imei
     *
     * @param imei the value for t_offer_delay.imei
     *
     * @mbggenerated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_delay.ip_address
     *
     * @return the value of t_offer_delay.ip_address
     *
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_delay.ip_address
     *
     * @param ipAddress the value for t_offer_delay.ip_address
     *
     * @mbggenerated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }
}