package szu.csbd.dto;

import java.util.Date;

public class OfferLiked {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_like.offer_like_id
     *
     * @mbggenerated
     */
    private Integer offerLikeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_like.offer_id
     *
     * @mbggenerated
     */
    private Integer offerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_like.offer_liked
     *
     * @mbggenerated
     */
    private Boolean offerLiked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_like.offer_liked_time
     *
     * @mbggenerated
     */
    private Date offerLikedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_like.imei
     *
     * @mbggenerated
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_like.ip_adress
     *
     * @mbggenerated
     */
    private String ipAdress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_like.offer_like_id
     *
     * @return the value of t_offer_like.offer_like_id
     *
     * @mbggenerated
     */
    public Integer getOfferLikeId() {
        return offerLikeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_like.offer_like_id
     *
     * @param offerLikeId the value for t_offer_like.offer_like_id
     *
     * @mbggenerated
     */
    public void setOfferLikeId(Integer offerLikeId) {
        this.offerLikeId = offerLikeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_like.offer_id
     *
     * @return the value of t_offer_like.offer_id
     *
     * @mbggenerated
     */
    public Integer getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_like.offer_id
     *
     * @param offerId the value for t_offer_like.offer_id
     *
     * @mbggenerated
     */
    public void setOfferId(Integer offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_like.offer_liked
     *
     * @return the value of t_offer_like.offer_liked
     *
     * @mbggenerated
     */
    public Boolean getOfferLiked() {
        return offerLiked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_like.offer_liked
     *
     * @param offerLiked the value for t_offer_like.offer_liked
     *
     * @mbggenerated
     */
    public void setOfferLiked(Boolean offerLiked) {
        this.offerLiked = offerLiked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_like.offer_liked_time
     *
     * @return the value of t_offer_like.offer_liked_time
     *
     * @mbggenerated
     */
    public Date getOfferLikedTime() {
        return offerLikedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_like.offer_liked_time
     *
     * @param offerLikedTime the value for t_offer_like.offer_liked_time
     *
     * @mbggenerated
     */
    public void setOfferLikedTime(Date offerLikedTime) {
        this.offerLikedTime = offerLikedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_like.imei
     *
     * @return the value of t_offer_like.imei
     *
     * @mbggenerated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_like.imei
     *
     * @param imei the value for t_offer_like.imei
     *
     * @mbggenerated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_like.ip_adress
     *
     * @return the value of t_offer_like.ip_adress
     *
     * @mbggenerated
     */
    public String getIpAdress() {
        return ipAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_like.ip_adress
     *
     * @param ipAdress the value for t_offer_like.ip_adress
     *
     * @mbggenerated
     */
    public void setIpAdress(String ipAdress) {
        this.ipAdress = ipAdress == null ? null : ipAdress.trim();
    }
}