package szu.csbd.dto;

import java.util.Date;

public class OfferView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_view.offer_view_id
     *
     * @mbggenerated
     */
    private Integer offerViewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_view.offer_id
     *
     * @mbggenerated
     */
    private Integer offerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_view.view_time
     *
     * @mbggenerated
     */
    private Date viewTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_view.imei
     *
     * @mbggenerated
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer_view.ip_adress
     *
     * @mbggenerated
     */
    private String ipAdress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_view.offer_view_id
     *
     * @return the value of t_offer_view.offer_view_id
     *
     * @mbggenerated
     */
    public Integer getOfferViewId() {
        return offerViewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_view.offer_view_id
     *
     * @param offerViewId the value for t_offer_view.offer_view_id
     *
     * @mbggenerated
     */
    public void setOfferViewId(Integer offerViewId) {
        this.offerViewId = offerViewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_view.offer_id
     *
     * @return the value of t_offer_view.offer_id
     *
     * @mbggenerated
     */
    public Integer getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_view.offer_id
     *
     * @param offerId the value for t_offer_view.offer_id
     *
     * @mbggenerated
     */
    public void setOfferId(Integer offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_view.view_time
     *
     * @return the value of t_offer_view.view_time
     *
     * @mbggenerated
     */
    public Date getViewTime() {
        return viewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_view.view_time
     *
     * @param viewTime the value for t_offer_view.view_time
     *
     * @mbggenerated
     */
    public void setViewTime(Date viewTime) {
        this.viewTime = viewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_view.imei
     *
     * @return the value of t_offer_view.imei
     *
     * @mbggenerated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_view.imei
     *
     * @param imei the value for t_offer_view.imei
     *
     * @mbggenerated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer_view.ip_adress
     *
     * @return the value of t_offer_view.ip_adress
     *
     * @mbggenerated
     */
    public String getIpAdress() {
        return ipAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer_view.ip_adress
     *
     * @param ipAdress the value for t_offer_view.ip_adress
     *
     * @mbggenerated
     */
    public void setIpAdress(String ipAdress) {
        this.ipAdress = ipAdress == null ? null : ipAdress.trim();
    }
}