package szu.csbd.mapper;

import szu.csbd.dto.CommentsRemark;

public interface CommentsRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remark_comments
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer remarkCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remark_comments
     *
     * @mbggenerated
     */
    int insert(CommentsRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remark_comments
     *
     * @mbggenerated
     */
    int insertSelective(CommentsRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remark_comments
     *
     * @mbggenerated
     */
    CommentsRemark selectByPrimaryKey(Integer remarkCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remark_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommentsRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remark_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CommentsRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remark_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommentsRemark record);
}