package szu.csbd.mapper;

import szu.csbd.dto.CommentsLiked;

public interface CommentsLikedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments_like
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commentLikeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments_like
     *
     * @mbggenerated
     */
    int insert(CommentsLiked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments_like
     *
     * @mbggenerated
     */
    int insertSelective(CommentsLiked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments_like
     *
     * @mbggenerated
     */
    CommentsLiked selectByPrimaryKey(Integer commentLikeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments_like
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommentsLiked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments_like
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CommentsLiked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments_like
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommentsLiked record);
}