package szu.csbd.mapper;

import szu.csbd.dto.OfferLiked;

public interface OfferLikedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_like
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer offerLikeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_like
     *
     * @mbggenerated
     */
    int insert(OfferLiked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_like
     *
     * @mbggenerated
     */
    int insertSelective(OfferLiked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_like
     *
     * @mbggenerated
     */
    OfferLiked selectByPrimaryKey(Integer offerLikeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_like
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfferLiked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_like
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OfferLiked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_like
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OfferLiked record);
}