package szu.csbd.mapper;

import szu.csbd.dto.OfferComments;

public interface OfferCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_comments
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer offerCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_comments
     *
     * @mbggenerated
     */
    int insert(OfferComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_comments
     *
     * @mbggenerated
     */
    int insertSelective(OfferComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_comments
     *
     * @mbggenerated
     */
    OfferComments selectByPrimaryKey(Integer offerCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfferComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OfferComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OfferComments record);
}