package szu.csbd.mapper;

import szu.csbd.dto.OfferCompany;

public interface OfferCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_company
     *
     * @mbggenerated
     */
    int insert(OfferCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_company
     *
     * @mbggenerated
     */
    int insertSelective(OfferCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_company
     *
     * @mbggenerated
     */
    OfferCompany selectByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfferCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OfferCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OfferCompany record);
}