package szu.csbd.mapper;

import szu.csbd.dto.OfferView;

public interface OfferViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_view
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer offerViewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_view
     *
     * @mbggenerated
     */
    int insert(OfferView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_view
     *
     * @mbggenerated
     */
    int insertSelective(OfferView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_view
     *
     * @mbggenerated
     */
    OfferView selectByPrimaryKey(Integer offerViewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_view
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfferView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_view
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OfferView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_view
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OfferView record);
}