package szu.csbd.mapper;

import szu.csbd.dto.OfferDelay;

public interface OfferDelayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_delay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer offerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_delay
     *
     * @mbggenerated
     */
    int insert(OfferDelay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_delay
     *
     * @mbggenerated
     */
    int insertSelective(OfferDelay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_delay
     *
     * @mbggenerated
     */
    OfferDelay selectByPrimaryKey(Integer offerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_delay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfferDelay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_delay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OfferDelay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_offer_delay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OfferDelay record);
}